"""empty message

Revision ID: 01b7f98b5ee5
Revises: 4720edc032c1
Create Date: 2021-08-10 23:01:52.800714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b7f98b5ee5'
down_revision = '4720edc032c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author', sa.String(length=500), nullable=True))
    op.add_column('book', sa.Column('categories', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_book_author'), 'book', ['author'], unique=False)
    op.create_index(op.f('ix_book_categories'), 'book', ['categories'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_categories'), table_name='book')
    op.drop_index(op.f('ix_book_author'), table_name='book')
    op.drop_column('book', 'categories')
    op.drop_column('book', 'author')
    # ### end Alembic commands ###
