"""empty message

Revision ID: 6d68044f25d0
Revises: 787d12f48068
Create Date: 2021-08-10 22:54:37.180160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d68044f25d0'
down_revision = '787d12f48068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_author', table_name='book')
    op.drop_index('ix_book_categories', table_name='book')
    op.drop_column('book', 'author')
    op.drop_column('book', 'categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('categories', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=True))
    op.add_column('book', sa.Column('author', postgresql.ARRAY(sa.VARCHAR(length=100)), autoincrement=False, nullable=True))
    op.create_index('ix_book_categories', 'book', ['categories'], unique=False)
    op.create_index('ix_book_author', 'book', ['author'], unique=False)
    # ### end Alembic commands ###
