"""empty message

Revision ID: 82ce4145a923
Revises: 1692132dbb10
Create Date: 2021-08-10 10:29:49.026508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82ce4145a923'
down_revision = '1692132dbb10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_author', table_name='book')
    op.drop_index('ix_book_categories', table_name='book')
    op.drop_index('ix_book_title', table_name='book')
    op.drop_index('ix_book_volume_id', table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('volume_id', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('author', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=True),
    sa.Column('subtitle', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], name='book_owner_fkey'),
    sa.PrimaryKeyConstraint('id', name='book_pkey')
    )
    op.create_index('ix_book_volume_id', 'book', ['volume_id'], unique=False)
    op.create_index('ix_book_title', 'book', ['title'], unique=False)
    op.create_index('ix_book_categories', 'book', ['categories'], unique=False)
    op.create_index('ix_book_author', 'book', ['author'], unique=False)
    # ### end Alembic commands ###
